SRCH-799: create search api endpoints
nice-digital/mocks-apis pull request #2
Opened 2022-12-19 09:37 UTC by dcmwong

2022-12-19 09:39 UTC, dcmwong commented
Open to changing the default port.  I've put it to 3000 as most Node projects I've worked on default to that port.

2022-12-19 10:41 UTC, ediblecode requested changes

2022-12-19 10:41 UTC, ediblecode commented on search-apis/Dockerfile
> +FROM node:14-alpine
Can we go straight to Node 18? Just cos 14 is EOL in 4 months...

2022-12-19 10:41 UTC, ediblecode commented on search-apis/package.json
> +  "name": "@nice-digital/cks-fake-elastic",
Can we call this something like `@nice-digital/mock-search-api` please?

2022-12-19 10:41 UTC, ediblecode commented on search-apis/package.json
> +  "homepage": "https://github.com/nice-digital/cks-gatsby/functional-tests/fake-elastic/#readme",
Can you update the homepage URL to the new mock APIs repo sub folder?

2022-12-19 10:41 UTC, ediblecode commented on search-apis/package.json
> +  "description": "Fake ElasticSearch instance for CKS automated tests",
Can you update the description?

2022-12-20 09:34 UTC, colinmazu approved these changes

2022-12-21 09:58 UTC, ediblecode approved these changes

2022-12-21 10:37 UTC, merged